# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [
    url(
        r'^address/list/$',
        views.AddressListView.as_view(),
        name='address_list'
    ),
    url(
        r'^address/retrieve/(?P<pk>\w+)/$',
        views.AddressRetrieveView.as_view(),
        name='address_retrieve'
    ),
    url(
        r'^address/create/$',
        views.AddressCreateView.as_view(),
        name='address_create'
    ),
    url(
        r'^address/partial-update/(?P<pk>\w+)/$',
        views.AddressPartialUpdateView.as_view(),
        name='address_partial_update'
    ),
    url(
        r'^address/destroy/(?P<pk>\w+)/$',
        views.AddressDestroyView.as_view(),
        name='address_destroy'
    ),
    url(
        r'^address/set-status/(?P<pk>\w+)/$',
        views.AddressSetStatusView.as_view(),
        name='address_set_status'
    ),
    url(
        r'^address/enable/(?P<pk>\w+)/$',
        views.AddressEnableView.as_view(),
        name='address_enable'
    ),
    url(
        r'^address/disable/(?P<pk>\w+)/$',
        views.AddressDisableView.as_view(),
        name='address_disable'
    ),
    url(
        r'^customer/list/$',
        views.CustomerListView.as_view(),
        name='customer_list'
    ),
    url(
        r'^customer/retrieve/(?P<pk>\w+)/$',
        views.CustomerRetrieveView.as_view(),
        name='customer_retrieve'
    ),
    url(
        r'^customer/create/$',
        views.CustomerCreateView.as_view(),
        name='customer_create'
    ),
    url(
        r'^customer/partial-update/(?P<pk>\w+)/$',
        views.CustomerPartialUpdateView.as_view(),
        name='customer_partial_update'
    ),
    url(
        r'^customer/destroy/(?P<pk>\w+)/$',
        views.CustomerDestroyView.as_view(),
        name='customer_destroy'
    ),
    url(
        r'^customer/set-status/(?P<pk>\w+)/$',
        views.CustomerSetStatusView.as_view(),
        name='customer_set_status'
    ),
    url(
        r'^customer/enable/(?P<pk>\w+)/$',
        views.CustomerEnableView.as_view(),
        name='customer_enable'
    ),
    url(
        r'^customer/disable/(?P<pk>\w+)/$',
        views.CustomerDisableView.as_view(),
        name='customer_disable'
    ),
    url(
        r'^energy_interval/list/$',
        views.Energy_intervalListView.as_view(),
        name='energy_interval_list'
    ),
    url(
        r'^energy_interval/retrieve/(?P<pk>\w+)/$',
        views.Energy_intervalRetrieveView.as_view(),
        name='energy_interval_retrieve'
    ),
    url(
        r'^energy_interval/create/$',
        views.Energy_intervalCreateView.as_view(),
        name='energy_interval_create'
    ),
    url(
        r'^energy_interval/partial-update/(?P<pk>\w+)/$',
        views.Energy_intervalPartialUpdateView.as_view(),
        name='energy_interval_partial_update'
    ),
    url(
        r'^energy_interval/destroy/(?P<pk>\w+)/$',
        views.Energy_intervalDestroyView.as_view(),
        name='energy_interval_destroy'
    ),
    url(
        r'^energy_interval/set-status/(?P<pk>\w+)/$',
        views.Energy_intervalSetStatusView.as_view(),
        name='energy_interval_set_status'
    ),
    url(
        r'^energy_interval/enable/(?P<pk>\w+)/$',
        views.Energy_intervalEnableView.as_view(),
        name='energy_interval_enable'
    ),
    url(
        r'^energy_interval/disable/(?P<pk>\w+)/$',
        views.Energy_intervalDisableView.as_view(),
        name='energy_interval_disable'
    ),
    url(
        r'^energy_meter_module/list/$',
        views.Energy_meter_moduleListView.as_view(),
        name='energy_meter_module_list'
    ),
    url(
        r'^energy_meter_module/retrieve/(?P<pk>\w+)/$',
        views.Energy_meter_moduleRetrieveView.as_view(),
        name='energy_meter_module_retrieve'
    ),
    url(
        r'^energy_meter_module/create/$',
        views.Energy_meter_moduleCreateView.as_view(),
        name='energy_meter_module_create'
    ),
    url(
        r'^energy_meter_module/partial-update/(?P<pk>\w+)/$',
        views.Energy_meter_modulePartialUpdateView.as_view(),
        name='energy_meter_module_partial_update'
    ),
    url(
        r'^energy_meter_module/destroy/(?P<pk>\w+)/$',
        views.Energy_meter_moduleDestroyView.as_view(),
        name='energy_meter_module_destroy'
    ),
    url(
        r'^energy_meter_module/set-status/(?P<pk>\w+)/$',
        views.Energy_meter_moduleSetStatusView.as_view(),
        name='energy_meter_module_set_status'
    ),
    url(
        r'^energy_meter_module/enable/(?P<pk>\w+)/$',
        views.Energy_meter_moduleEnableView.as_view(),
        name='energy_meter_module_enable'
    ),
    url(
        r'^energy_meter_module/disable/(?P<pk>\w+)/$',
        views.Energy_meter_moduleDisableView.as_view(),
        name='energy_meter_module_disable'
    ),
    url(
        r'^energy_meter_peak_measure/list/$',
        views.Energy_meter_peak_measureListView.as_view(),
        name='energy_meter_peak_measure_list'
    ),
    url(
        r'^energy_meter_peak_measure/retrieve/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureRetrieveView.as_view(),
        name='energy_meter_peak_measure_retrieve'
    ),
    url(
        r'^energy_meter_peak_measure/create/$',
        views.Energy_meter_peak_measureCreateView.as_view(),
        name='energy_meter_peak_measure_create'
    ),
    url(
        r'^energy_meter_peak_measure/partial-update/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measurePartialUpdateView.as_view(),
        name='energy_meter_peak_measure_partial_update'
    ),
    url(
        r'^energy_meter_peak_measure/destroy/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureDestroyView.as_view(),
        name='energy_meter_peak_measure_destroy'
    ),
    url(
        r'^energy_meter_peak_measure/set-status/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureSetStatusView.as_view(),
        name='energy_meter_peak_measure_set_status'
    ),
    url(
        r'^energy_meter_peak_measure/enable/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureEnableView.as_view(),
        name='energy_meter_peak_measure_enable'
    ),
    url(
        r'^energy_meter_peak_measure/disable/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureDisableView.as_view(),
        name='energy_meter_peak_measure_disable'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/list/$',
        views.Error_light_level_and_adc_mismatchListView.as_view(),
        name='error_light_level_and_adc_mismatch_list'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/retrieve/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchRetrieveView.as_view(),
        name='error_light_level_and_adc_mismatch_retrieve'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/create/$',
        views.Error_light_level_and_adc_mismatchCreateView.as_view(),
        name='error_light_level_and_adc_mismatch_create'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/partial-update/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchPartialUpdateView.as_view(),
        name='error_light_level_and_adc_mismatch_partial_update'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/destroy/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchDestroyView.as_view(),
        name='error_light_level_and_adc_mismatch_destroy'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/set-status/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchSetStatusView.as_view(),
        name='error_light_level_and_adc_mismatch_set_status'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/enable/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchEnableView.as_view(),
        name='error_light_level_and_adc_mismatch_enable'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/disable/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchDisableView.as_view(),
        name='error_light_level_and_adc_mismatch_disable'
    ),
    url(
        r'^error_light_level_and_power_mismatch/list/$',
        views.Error_light_level_and_power_mismatchListView.as_view(),
        name='error_light_level_and_power_mismatch_list'
    ),
    url(
        r'^error_light_level_and_power_mismatch/retrieve/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchRetrieveView.as_view(),
        name='error_light_level_and_power_mismatch_retrieve'
    ),
    url(
        r'^error_light_level_and_power_mismatch/create/$',
        views.Error_light_level_and_power_mismatchCreateView.as_view(),
        name='error_light_level_and_power_mismatch_create'
    ),
    url(
        r'^error_light_level_and_power_mismatch/partial-update/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchPartialUpdateView.as_view(),
        name='error_light_level_and_power_mismatch_partial_update'
    ),
    url(
        r'^error_light_level_and_power_mismatch/destroy/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchDestroyView.as_view(),
        name='error_light_level_and_power_mismatch_destroy'
    ),
    url(
        r'^error_light_level_and_power_mismatch/set-status/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchSetStatusView.as_view(),
        name='error_light_level_and_power_mismatch_set_status'
    ),
    url(
        r'^error_light_level_and_power_mismatch/enable/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchEnableView.as_view(),
        name='error_light_level_and_power_mismatch_enable'
    ),
    url(
        r'^error_light_level_and_power_mismatch/disable/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchDisableView.as_view(),
        name='error_light_level_and_power_mismatch_disable'
    ),
    url(
        r'^error_node_offline/list/$',
        views.Error_node_offlineListView.as_view(),
        name='error_node_offline_list'
    ),
    url(
        r'^error_node_offline/retrieve/(?P<pk>\w+)/$',
        views.Error_node_offlineRetrieveView.as_view(),
        name='error_node_offline_retrieve'
    ),
    url(
        r'^error_node_offline/create/$',
        views.Error_node_offlineCreateView.as_view(),
        name='error_node_offline_create'
    ),
    url(
        r'^error_node_offline/partial-update/(?P<pk>\w+)/$',
        views.Error_node_offlinePartialUpdateView.as_view(),
        name='error_node_offline_partial_update'
    ),
    url(
        r'^error_node_offline/destroy/(?P<pk>\w+)/$',
        views.Error_node_offlineDestroyView.as_view(),
        name='error_node_offline_destroy'
    ),
    url(
        r'^error_node_offline/set-status/(?P<pk>\w+)/$',
        views.Error_node_offlineSetStatusView.as_view(),
        name='error_node_offline_set_status'
    ),
    url(
        r'^error_node_offline/enable/(?P<pk>\w+)/$',
        views.Error_node_offlineEnableView.as_view(),
        name='error_node_offline_enable'
    ),
    url(
        r'^error_node_offline/disable/(?P<pk>\w+)/$',
        views.Error_node_offlineDisableView.as_view(),
        name='error_node_offline_disable'
    ),
    url(
        r'^gateway/list/$',
        views.GatewayListView.as_view(),
        name='gateway_list'
    ),
    url(
        r'^gateway/retrieve/(?P<pk>\w+)/$',
        views.GatewayRetrieveView.as_view(),
        name='gateway_retrieve'
    ),
    url(
        r'^gateway/create/$',
        views.GatewayCreateView.as_view(),
        name='gateway_create'
    ),
    url(
        r'^gateway/partial-update/(?P<pk>\w+)/$',
        views.GatewayPartialUpdateView.as_view(),
        name='gateway_partial_update'
    ),
    url(
        r'^gateway/destroy/(?P<pk>\w+)/$',
        views.GatewayDestroyView.as_view(),
        name='gateway_destroy'
    ),
    url(
        r'^gateway/set-status/(?P<pk>\w+)/$',
        views.GatewaySetStatusView.as_view(),
        name='gateway_set_status'
    ),
    url(
        r'^gateway/enable/(?P<pk>\w+)/$',
        views.GatewayEnableView.as_view(),
        name='gateway_enable'
    ),
    url(
        r'^gateway/disable/(?P<pk>\w+)/$',
        views.GatewayDisableView.as_view(),
        name='gateway_disable'
    ),
    url(
        r'^ime_power_counter/list/$',
        views.Ime_power_counterListView.as_view(),
        name='ime_power_counter_list'
    ),
    url(
        r'^ime_power_counter/retrieve/(?P<pk>\w+)/$',
        views.Ime_power_counterRetrieveView.as_view(),
        name='ime_power_counter_retrieve'
    ),
    url(
        r'^ime_power_counter/create/$',
        views.Ime_power_counterCreateView.as_view(),
        name='ime_power_counter_create'
    ),
    url(
        r'^ime_power_counter/partial-update/(?P<pk>\w+)/$',
        views.Ime_power_counterPartialUpdateView.as_view(),
        name='ime_power_counter_partial_update'
    ),
    url(
        r'^ime_power_counter/destroy/(?P<pk>\w+)/$',
        views.Ime_power_counterDestroyView.as_view(),
        name='ime_power_counter_destroy'
    ),
    url(
        r'^ime_power_counter/set-status/(?P<pk>\w+)/$',
        views.Ime_power_counterSetStatusView.as_view(),
        name='ime_power_counter_set_status'
    ),
    url(
        r'^ime_power_counter/enable/(?P<pk>\w+)/$',
        views.Ime_power_counterEnableView.as_view(),
        name='ime_power_counter_enable'
    ),
    url(
        r'^ime_power_counter/disable/(?P<pk>\w+)/$',
        views.Ime_power_counterDisableView.as_view(),
        name='ime_power_counter_disable'
    ),
    url(
        r'^ime_power_measure/list/$',
        views.Ime_power_measureListView.as_view(),
        name='ime_power_measure_list'
    ),
    url(
        r'^ime_power_measure/retrieve/(?P<pk>\w+)/$',
        views.Ime_power_measureRetrieveView.as_view(),
        name='ime_power_measure_retrieve'
    ),
    url(
        r'^ime_power_measure/create/$',
        views.Ime_power_measureCreateView.as_view(),
        name='ime_power_measure_create'
    ),
    url(
        r'^ime_power_measure/partial-update/(?P<pk>\w+)/$',
        views.Ime_power_measurePartialUpdateView.as_view(),
        name='ime_power_measure_partial_update'
    ),
    url(
        r'^ime_power_measure/destroy/(?P<pk>\w+)/$',
        views.Ime_power_measureDestroyView.as_view(),
        name='ime_power_measure_destroy'
    ),
    url(
        r'^ime_power_measure/set-status/(?P<pk>\w+)/$',
        views.Ime_power_measureSetStatusView.as_view(),
        name='ime_power_measure_set_status'
    ),
    url(
        r'^ime_power_measure/enable/(?P<pk>\w+)/$',
        views.Ime_power_measureEnableView.as_view(),
        name='ime_power_measure_enable'
    ),
    url(
        r'^ime_power_measure/disable/(?P<pk>\w+)/$',
        views.Ime_power_measureDisableView.as_view(),
        name='ime_power_measure_disable'
    ),
    url(
        r'^installation/list/$',
        views.InstallationListView.as_view(),
        name='installation_list'
    ),
    url(
        r'^installation/retrieve/(?P<pk>\w+)/$',
        views.InstallationRetrieveView.as_view(),
        name='installation_retrieve'
    ),
    url(
        r'^installation/create/$',
        views.InstallationCreateView.as_view(),
        name='installation_create'
    ),
    url(
        r'^installation/partial-update/(?P<pk>\w+)/$',
        views.InstallationPartialUpdateView.as_view(),
        name='installation_partial_update'
    ),
    url(
        r'^installation/destroy/(?P<pk>\w+)/$',
        views.InstallationDestroyView.as_view(),
        name='installation_destroy'
    ),
    url(
        r'^installation/set-status/(?P<pk>\w+)/$',
        views.InstallationSetStatusView.as_view(),
        name='installation_set_status'
    ),
    url(
        r'^installation/enable/(?P<pk>\w+)/$',
        views.InstallationEnableView.as_view(),
        name='installation_enable'
    ),
    url(
        r'^installation/disable/(?P<pk>\w+)/$',
        views.InstallationDisableView.as_view(),
        name='installation_disable'
    ),
    url(
        r'^light_management_measure/list/$',
        views.Light_management_measureListView.as_view(),
        name='light_management_measure_list'
    ),
    url(
        r'^light_management_measure/retrieve/(?P<pk>\w+)/$',
        views.Light_management_measureRetrieveView.as_view(),
        name='light_management_measure_retrieve'
    ),
    url(
        r'^light_management_measure/create/$',
        views.Light_management_measureCreateView.as_view(),
        name='light_management_measure_create'
    ),
    url(
        r'^light_management_measure/partial-update/(?P<pk>\w+)/$',
        views.Light_management_measurePartialUpdateView.as_view(),
        name='light_management_measure_partial_update'
    ),
    url(
        r'^light_management_measure/destroy/(?P<pk>\w+)/$',
        views.Light_management_measureDestroyView.as_view(),
        name='light_management_measure_destroy'
    ),
    url(
        r'^light_management_measure/set-status/(?P<pk>\w+)/$',
        views.Light_management_measureSetStatusView.as_view(),
        name='light_management_measure_set_status'
    ),
    url(
        r'^light_management_measure/enable/(?P<pk>\w+)/$',
        views.Light_management_measureEnableView.as_view(),
        name='light_management_measure_enable'
    ),
    url(
        r'^light_management_measure/disable/(?P<pk>\w+)/$',
        views.Light_management_measureDisableView.as_view(),
        name='light_management_measure_disable'
    ),
    url(
        r'^light_management_module/list/$',
        views.Light_management_moduleListView.as_view(),
        name='light_management_module_list'
    ),
    url(
        r'^light_management_module/retrieve/(?P<pk>\w+)/$',
        views.Light_management_moduleRetrieveView.as_view(),
        name='light_management_module_retrieve'
    ),
    url(
        r'^light_management_module/create/$',
        views.Light_management_moduleCreateView.as_view(),
        name='light_management_module_create'
    ),
    url(
        r'^light_management_module/partial-update/(?P<pk>\w+)/$',
        views.Light_management_modulePartialUpdateView.as_view(),
        name='light_management_module_partial_update'
    ),
    url(
        r'^light_management_module/destroy/(?P<pk>\w+)/$',
        views.Light_management_moduleDestroyView.as_view(),
        name='light_management_module_destroy'
    ),
    url(
        r'^light_management_module/set-status/(?P<pk>\w+)/$',
        views.Light_management_moduleSetStatusView.as_view(),
        name='light_management_module_set_status'
    ),
    url(
        r'^light_management_module/enable/(?P<pk>\w+)/$',
        views.Light_management_moduleEnableView.as_view(),
        name='light_management_module_enable'
    ),
    url(
        r'^light_management_module/disable/(?P<pk>\w+)/$',
        views.Light_management_moduleDisableView.as_view(),
        name='light_management_module_disable'
    ),
    url(
        r'^light_profile/list/$',
        views.Light_profileListView.as_view(),
        name='light_profile_list'
    ),
    url(
        r'^light_profile/retrieve/(?P<pk>\w+)/$',
        views.Light_profileRetrieveView.as_view(),
        name='light_profile_retrieve'
    ),
    url(
        r'^light_profile/create/$',
        views.Light_profileCreateView.as_view(),
        name='light_profile_create'
    ),
    url(
        r'^light_profile/partial-update/(?P<pk>\w+)/$',
        views.Light_profilePartialUpdateView.as_view(),
        name='light_profile_partial_update'
    ),
    url(
        r'^light_profile/destroy/(?P<pk>\w+)/$',
        views.Light_profileDestroyView.as_view(),
        name='light_profile_destroy'
    ),
    url(
        r'^light_profile/set-status/(?P<pk>\w+)/$',
        views.Light_profileSetStatusView.as_view(),
        name='light_profile_set_status'
    ),
    url(
        r'^light_profile/enable/(?P<pk>\w+)/$',
        views.Light_profileEnableView.as_view(),
        name='light_profile_enable'
    ),
    url(
        r'^light_profile/disable/(?P<pk>\w+)/$',
        views.Light_profileDisableView.as_view(),
        name='light_profile_disable'
    ),
    url(
        r'^light_profile_slot/list/$',
        views.Light_profile_slotListView.as_view(),
        name='light_profile_slot_list'
    ),
    url(
        r'^light_profile_slot/retrieve/(?P<pk>\w+)/$',
        views.Light_profile_slotRetrieveView.as_view(),
        name='light_profile_slot_retrieve'
    ),
    url(
        r'^light_profile_slot/create/$',
        views.Light_profile_slotCreateView.as_view(),
        name='light_profile_slot_create'
    ),
    url(
        r'^light_profile_slot/partial-update/(?P<pk>\w+)/$',
        views.Light_profile_slotPartialUpdateView.as_view(),
        name='light_profile_slot_partial_update'
    ),
    url(
        r'^light_profile_slot/destroy/(?P<pk>\w+)/$',
        views.Light_profile_slotDestroyView.as_view(),
        name='light_profile_slot_destroy'
    ),
    url(
        r'^light_profile_slot/set-status/(?P<pk>\w+)/$',
        views.Light_profile_slotSetStatusView.as_view(),
        name='light_profile_slot_set_status'
    ),
    url(
        r'^light_profile_slot/enable/(?P<pk>\w+)/$',
        views.Light_profile_slotEnableView.as_view(),
        name='light_profile_slot_enable'
    ),
    url(
        r'^light_profile_slot/disable/(?P<pk>\w+)/$',
        views.Light_profile_slotDisableView.as_view(),
        name='light_profile_slot_disable'
    ),
    url(
        r'^motion_event/list/$',
        views.Motion_eventListView.as_view(),
        name='motion_event_list'
    ),
    url(
        r'^motion_event/retrieve/(?P<pk>\w+)/$',
        views.Motion_eventRetrieveView.as_view(),
        name='motion_event_retrieve'
    ),
    url(
        r'^motion_event/create/$',
        views.Motion_eventCreateView.as_view(),
        name='motion_event_create'
    ),
    url(
        r'^motion_event/partial-update/(?P<pk>\w+)/$',
        views.Motion_eventPartialUpdateView.as_view(),
        name='motion_event_partial_update'
    ),
    url(
        r'^motion_event/destroy/(?P<pk>\w+)/$',
        views.Motion_eventDestroyView.as_view(),
        name='motion_event_destroy'
    ),
    url(
        r'^motion_event/set-status/(?P<pk>\w+)/$',
        views.Motion_eventSetStatusView.as_view(),
        name='motion_event_set_status'
    ),
    url(
        r'^motion_event/enable/(?P<pk>\w+)/$',
        views.Motion_eventEnableView.as_view(),
        name='motion_event_enable'
    ),
    url(
        r'^motion_event/disable/(?P<pk>\w+)/$',
        views.Motion_eventDisableView.as_view(),
        name='motion_event_disable'
    ),
    url(
        r'^node/list/$',
        views.NodeListView.as_view(),
        name='node_list'
    ),
    url(
        r'^node/retrieve/(?P<pk>\w+)/$',
        views.NodeRetrieveView.as_view(),
        name='node_retrieve'
    ),
    url(
        r'^node/create/$',
        views.NodeCreateView.as_view(),
        name='node_create'
    ),
    url(
        r'^node/partial-update/(?P<pk>\w+)/$',
        views.NodePartialUpdateView.as_view(),
        name='node_partial_update'
    ),
    url(
        r'^node/destroy/(?P<pk>\w+)/$',
        views.NodeDestroyView.as_view(),
        name='node_destroy'
    ),
    url(
        r'^node/set-status/(?P<pk>\w+)/$',
        views.NodeSetStatusView.as_view(),
        name='node_set_status'
    ),
    url(
        r'^node/enable/(?P<pk>\w+)/$',
        views.NodeEnableView.as_view(),
        name='node_enable'
    ),
    url(
        r'^node/disable/(?P<pk>\w+)/$',
        views.NodeDisableView.as_view(),
        name='node_disable'
    ),
    url(
        r'^node_module/list/$',
        views.Node_moduleListView.as_view(),
        name='node_module_list'
    ),
    url(
        r'^node_module/retrieve/(?P<pk>\w+)/$',
        views.Node_moduleRetrieveView.as_view(),
        name='node_module_retrieve'
    ),
    url(
        r'^node_module/create/$',
        views.Node_moduleCreateView.as_view(),
        name='node_module_create'
    ),
    url(
        r'^node_module/partial-update/(?P<pk>\w+)/$',
        views.Node_modulePartialUpdateView.as_view(),
        name='node_module_partial_update'
    ),
    url(
        r'^node_module/destroy/(?P<pk>\w+)/$',
        views.Node_moduleDestroyView.as_view(),
        name='node_module_destroy'
    ),
    url(
        r'^node_module/set-status/(?P<pk>\w+)/$',
        views.Node_moduleSetStatusView.as_view(),
        name='node_module_set_status'
    ),
    url(
        r'^node_module/enable/(?P<pk>\w+)/$',
        views.Node_moduleEnableView.as_view(),
        name='node_module_enable'
    ),
    url(
        r'^node_module/disable/(?P<pk>\w+)/$',
        views.Node_moduleDisableView.as_view(),
        name='node_module_disable'
    ),
    url(
        r'^wilamp_alert/list/$',
        views.Wilamp_alertListView.as_view(),
        name='wilamp_alert_list'
    ),
    url(
        r'^wilamp_alert/retrieve/(?P<pk>\w+)/$',
        views.Wilamp_alertRetrieveView.as_view(),
        name='wilamp_alert_retrieve'
    ),
    url(
        r'^wilamp_alert/create/$',
        views.Wilamp_alertCreateView.as_view(),
        name='wilamp_alert_create'
    ),
    url(
        r'^wilamp_alert/partial-update/(?P<pk>\w+)/$',
        views.Wilamp_alertPartialUpdateView.as_view(),
        name='wilamp_alert_partial_update'
    ),
    url(
        r'^wilamp_alert/destroy/(?P<pk>\w+)/$',
        views.Wilamp_alertDestroyView.as_view(),
        name='wilamp_alert_destroy'
    ),
    url(
        r'^wilamp_alert/set-status/(?P<pk>\w+)/$',
        views.Wilamp_alertSetStatusView.as_view(),
        name='wilamp_alert_set_status'
    ),
    url(
        r'^wilamp_alert/enable/(?P<pk>\w+)/$',
        views.Wilamp_alertEnableView.as_view(),
        name='wilamp_alert_enable'
    ),
    url(
        r'^wilamp_alert/disable/(?P<pk>\w+)/$',
        views.Wilamp_alertDisableView.as_view(),
        name='wilamp_alert_disable'
    ),
    url(
        r'^feeder_pillar/list/$',
        views.Feeder_pillarListView.as_view(),
        name='feeder_pillar_list'
    ),
    url(
        r'^feeder_pillar/retrieve/(?P<pk>\w+)/$',
        views.Feeder_pillarRetrieveView.as_view(),
        name='feeder_pillar_retrieve'
    ),
    url(
        r'^feeder_pillar/create/$',
        views.Feeder_pillarCreateView.as_view(),
        name='feeder_pillar_create'
    ),
    url(
        r'^feeder_pillar/partial-update/(?P<pk>\w+)/$',
        views.Feeder_pillarPartialUpdateView.as_view(),
        name='feeder_pillar_partial_update'
    ),
    url(
        r'^feeder_pillar/destroy/(?P<pk>\w+)/$',
        views.Feeder_pillarDestroyView.as_view(),
        name='feeder_pillar_destroy'
    ),
    url(
        r'^feeder_pillar/set-status/(?P<pk>\w+)/$',
        views.Feeder_pillarSetStatusView.as_view(),
        name='feeder_pillar_set_status'
    ),
    url(
        r'^feeder_pillar/enable/(?P<pk>\w+)/$',
        views.Feeder_pillarEnableView.as_view(),
        name='feeder_pillar_enable'
    ),
    url(
        r'^feeder_pillar/disable/(?P<pk>\w+)/$',
        views.Feeder_pillarDisableView.as_view(),
        name='feeder_pillar_disable'
    ),
    url(
        r'^twilight_management_module/list/$',
        views.Twilight_management_moduleListView.as_view(),
        name='twilight_management_module_list'
    ),
    url(
        r'^twilight_management_module/retrieve/(?P<pk>\w+)/$',
        views.Twilight_management_moduleRetrieveView.as_view(),
        name='twilight_management_module_retrieve'
    ),
    url(
        r'^twilight_management_module/create/$',
        views.Twilight_management_moduleCreateView.as_view(),
        name='twilight_management_module_create'
    ),
    url(
        r'^twilight_management_module/partial-update/(?P<pk>\w+)/$',
        views.Twilight_management_modulePartialUpdateView.as_view(),
        name='twilight_management_module_partial_update'
    ),
    url(
        r'^twilight_management_module/destroy/(?P<pk>\w+)/$',
        views.Twilight_management_moduleDestroyView.as_view(),
        name='twilight_management_module_destroy'
    ),
    url(
        r'^twilight_management_module/set-status/(?P<pk>\w+)/$',
        views.Twilight_management_moduleSetStatusView.as_view(),
        name='twilight_management_module_set_status'
    ),
    url(
        r'^twilight_management_module/enable/(?P<pk>\w+)/$',
        views.Twilight_management_moduleEnableView.as_view(),
        name='twilight_management_module_enable'
    ),
    url(
        r'^twilight_management_module/disable/(?P<pk>\w+)/$',
        views.Twilight_management_moduleDisableView.as_view(),
        name='twilight_management_module_disable'
    ),
    url(
        r'^twilight_measure/list/$',
        views.Twilight_measureListView.as_view(),
        name='twilight_measure_list'
    ),
    url(
        r'^twilight_measure/retrieve/(?P<pk>\w+)/$',
        views.Twilight_measureRetrieveView.as_view(),
        name='twilight_measure_retrieve'
    ),
    url(
        r'^twilight_measure/create/$',
        views.Twilight_measureCreateView.as_view(),
        name='twilight_measure_create'
    ),
    url(
        r'^twilight_measure/partial-update/(?P<pk>\w+)/$',
        views.Twilight_measurePartialUpdateView.as_view(),
        name='twilight_measure_partial_update'
    ),
    url(
        r'^twilight_measure/destroy/(?P<pk>\w+)/$',
        views.Twilight_measureDestroyView.as_view(),
        name='twilight_measure_destroy'
    ),
    url(
        r'^twilight_measure/set-status/(?P<pk>\w+)/$',
        views.Twilight_measureSetStatusView.as_view(),
        name='twilight_measure_set_status'
    ),
    url(
        r'^twilight_measure/enable/(?P<pk>\w+)/$',
        views.Twilight_measureEnableView.as_view(),
        name='twilight_measure_enable'
    ),
    url(
        r'^twilight_measure/disable/(?P<pk>\w+)/$',
        views.Twilight_measureDisableView.as_view(),
        name='twilight_measure_disable'
    ),
    url(
        r'^motion_management_module/list/$',
        views.Motion_management_moduleListView.as_view(),
        name='motion_management_module_list'
    ),
    url(
        r'^motion_management_module/retrieve/(?P<pk>\w+)/$',
        views.Motion_management_moduleRetrieveView.as_view(),
        name='motion_management_module_retrieve'
    ),
    url(
        r'^motion_management_module/create/$',
        views.Motion_management_moduleCreateView.as_view(),
        name='motion_management_module_create'
    ),
    url(
        r'^motion_management_module/partial-update/(?P<pk>\w+)/$',
        views.Motion_management_modulePartialUpdateView.as_view(),
        name='motion_management_module_partial_update'
    ),
    url(
        r'^motion_management_module/destroy/(?P<pk>\w+)/$',
        views.Motion_management_moduleDestroyView.as_view(),
        name='motion_management_module_destroy'
    ),
    url(
        r'^motion_management_module/set-status/(?P<pk>\w+)/$',
        views.Motion_management_moduleSetStatusView.as_view(),
        name='motion_management_module_set_status'
    ),
    url(
        r'^motion_management_module/enable/(?P<pk>\w+)/$',
        views.Motion_management_moduleEnableView.as_view(),
        name='motion_management_module_enable'
    ),
    url(
        r'^motion_management_module/disable/(?P<pk>\w+)/$',
        views.Motion_management_moduleDisableView.as_view(),
        name='motion_management_module_disable'
    ),
    url(r'^user/change-password/',
        views.UserChangePasswordView.as_view(),
        name='users_change_password'
        ),
    url(r'^$', views.api_root, name='api_root'),
]
