# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

app_name = 'api'

urlpatterns = [

    url(
        regex=r'address/$',
        view=views.AddressListCreateAPIView.as_view(),
        name='address_list'
    ),

    url(
        regex=r'address/(?P<id>[-\w]+)/$',
        view=views.AddressRetrieveUpdateDestroyAPIView.as_view(),
        name='address_detail'
    ),
    url(
        r'^address/set-status/(?P<pk>\w+)/$',
        views.AddressSetStatusView.as_view(),
        name='address_set_status'
    ),
    url(
        r'^address/enable/(?P<pk>\w+)/$',
        views.AddressEnableView.as_view(),
        name='address_enable'
    ),
    url(
        r'^address/disable/(?P<pk>\w+)/$',
        views.AddressDisableView.as_view(),
        name='address_disable'
    ),
    url(
        r'^customer/$',
        views.CustomerListCreateAPIView.as_view(),
        name='customer_list'
    ),
    url(
        r'^customer/(?P<id>[-\w]+)/$',
        views.CustomerRetrieveUpdateDestroyAPIView.as_view(),
        name='customer_detail'
    ),
    url(
        r'^customer/set-status/(?P<pk>\w+)/$',
        views.CustomerSetStatusView.as_view(),
        name='customer_set_status'
    ),
    url(
        r'^customer/enable/(?P<pk>\w+)/$',
        views.CustomerEnableView.as_view(),
        name='customer_enable'
    ),
    url(
        r'^customer/disable/(?P<pk>\w+)/$',
        views.CustomerDisableView.as_view(),
        name='customer_disable'
    ),
    url(
        r'^energy_interval/$',
        views.Energy_intervalListCreateAPIView.as_view(),
        name='energy_interval_list'
    ),
    url(
        r'^energy_interval/(?P<id>[-\w]+)/$',
        views.Energy_intervalRetrieveUpdateDestroyAPIView.as_view(),
        name='energy_interval_detail'
    ),
    url(
        r'^energy_interval/set-status/(?P<pk>\w+)/$',
        views.Energy_intervalSetStatusView.as_view(),
        name='energy_interval_set_status'
    ),
    url(
        r'^energy_interval/enable/(?P<pk>\w+)/$',
        views.Energy_intervalEnableView.as_view(),
        name='energy_interval_enable'
    ),
    url(
        r'^energy_interval/disable/(?P<pk>\w+)/$',
        views.Energy_intervalDisableView.as_view(),
        name='energy_interval_disable'
    ),
    url(
        r'^energy_meter_module/$',
        views.Energy_meter_moduleListCreateAPIView.as_view(),
        name='energy_meter_module_list'
    ),
    url(
        r'^energy_meter_module/(?P<id>[-\w]+)/$',
        views.Energy_meter_moduleRetrieveUpdateDestroyAPIView.as_view(),
        name='energy_meter_module_detail'
    ),
    url(
        r'^energy_meter_module/set-status/(?P<pk>\w+)/$',
        views.Energy_meter_moduleSetStatusView.as_view(),
        name='energy_meter_module_set_status'
    ),
    url(
        r'^energy_meter_module/enable/(?P<pk>\w+)/$',
        views.Energy_meter_moduleEnableView.as_view(),
        name='energy_meter_module_enable'
    ),
    url(
        r'^energy_meter_module/disable/(?P<pk>\w+)/$',
        views.Energy_meter_moduleDisableView.as_view(),
        name='energy_meter_module_disable'
    ),
    url(
        r'^energy_meter_peak_measure/$',
        views.Energy_meter_peak_measureListCreateAPIView.as_view(),
        name='energy_meter_peak_measure_list'
    ),
    url(
        r'^energy_meter_peak_measure/(?P<id>[-\w]+)/$',
        views.Energy_meter_peak_measureRetrieveUpdateDestroyAPIView.as_view(),
        name='energy_meter_peak_measure_detail'
    ),
    url(
        r'^energy_meter_peak_measure/set-status/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureSetStatusView.as_view(),
        name='energy_meter_peak_measure_set_status'
    ),
    url(
        r'^energy_meter_peak_measure/enable/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureEnableView.as_view(),
        name='energy_meter_peak_measure_enable'
    ),
    url(
        r'^energy_meter_peak_measure/disable/(?P<pk>\w+)/$',
        views.Energy_meter_peak_measureDisableView.as_view(),
        name='energy_meter_peak_measure_disable'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/$',
        views.Error_light_level_and_adc_mismatchListCreateAPIView.as_view(),
        name='error_light_level_and_adc_mismatch_list'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/(?P<id>[-\w]+)/$',
        views.Error_light_level_and_adc_mismatchRetrieveUpdateDestroyAPIView.as_view(),
        name='error_light_level_and_adc_mismatch_detail'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/set-status/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchSetStatusView.as_view(),
        name='error_light_level_and_adc_mismatch_set_status'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/enable/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchEnableView.as_view(),
        name='error_light_level_and_adc_mismatch_enable'
    ),
    url(
        r'^error_light_level_and_adc_mismatch/disable/(?P<pk>\w+)/$',
        views.Error_light_level_and_adc_mismatchDisableView.as_view(),
        name='error_light_level_and_adc_mismatch_disable'
    ),
    url(
        r'^error_light_level_and_power_mismatch/$',
        views.Error_light_level_and_power_mismatchListCreateAPIView.as_view(),
        name='error_light_level_and_power_mismatch_list'
    ),
    url(
        r'^error_light_level_and_power_mismatch/(?P<id>[-\w]+)/$',
        views.Error_light_level_and_power_mismatchRetrieveUpdateDestroyAPIView.as_view(),
        name='error_light_level_and_power_mismatch_detail'
    ),
    url(
        r'^error_light_level_and_power_mismatch/set-status/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchSetStatusView.as_view(),
        name='error_light_level_and_power_mismatch_set_status'
    ),
    url(
        r'^error_light_level_and_power_mismatch/enable/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchEnableView.as_view(),
        name='error_light_level_and_power_mismatch_enable'
    ),
    url(
        r'^error_light_level_and_power_mismatch/disable/(?P<pk>\w+)/$',
        views.Error_light_level_and_power_mismatchDisableView.as_view(),
        name='error_light_level_and_power_mismatch_disable'
    ),
    url(
        r'^error_node_offline/$',
        views.Error_node_offlineListCreateAPIView.as_view(),
        name='error_node_offline_list'
    ),
    url(
        r'^error_node_offline/(?P<id>[-\w]+)/$',
        views.Error_node_offlineRetrieveUpdateDestroyAPIView.as_view(),
        name='error_node_offline_detail'
    ),
    url(
        r'^error_node_offline/set-status/(?P<pk>\w+)/$',
        views.Error_node_offlineSetStatusView.as_view(),
        name='error_node_offline_set_status'
    ),
    url(
        r'^error_node_offline/enable/(?P<pk>\w+)/$',
        views.Error_node_offlineEnableView.as_view(),
        name='error_node_offline_enable'
    ),
    url(
        r'^error_node_offline/disable/(?P<pk>\w+)/$',
        views.Error_node_offlineDisableView.as_view(),
        name='error_node_offline_disable'
    ),
    url(
        r'^gateway/$',
        views.GatewayListCreateAPIView.as_view(),
        name='gateway_list'
    ),
    url(
        r'^gateway/(?P<id>[-\w]+)/$',
        views.GatewayRetrieveUpdateDestroyAPIView.as_view(),
        name='gateway_detail'
    ),
    url(
        r'^gateway/set-status/(?P<pk>\w+)/$',
        views.GatewaySetStatusView.as_view(),
        name='gateway_set_status'
    ),
    url(
        r'^gateway/enable/(?P<pk>\w+)/$',
        views.GatewayEnableView.as_view(),
        name='gateway_enable'
    ),
    url(
        r'^gateway/disable/(?P<pk>\w+)/$',
        views.GatewayDisableView.as_view(),
        name='gateway_disable'
    ),
    url(
        r'^ime_power_counter/$',
        views.Ime_power_counterListCreateAPIView.as_view(),
        name='ime_power_counter_list'
    ),
    url(
        r'^ime_power_counter/(?P<id>[-\w]+)/$',
        views.Ime_power_counterRetrieveUpdateDestroyAPIView.as_view(),
        name='ime_power_counter_detail'
    ),
    url(
        r'^ime_power_counter/set-status/(?P<pk>\w+)/$',
        views.Ime_power_counterSetStatusView.as_view(),
        name='ime_power_counter_set_status'
    ),
    url(
        r'^ime_power_counter/enable/(?P<pk>\w+)/$',
        views.Ime_power_counterEnableView.as_view(),
        name='ime_power_counter_enable'
    ),
    url(
        r'^ime_power_counter/disable/(?P<pk>\w+)/$',
        views.Ime_power_counterDisableView.as_view(),
        name='ime_power_counter_disable'
    ),
    url(
        r'^ime_power_measure/$',
        views.Ime_power_measureListCreateAPIView.as_view(),
        name='ime_power_measure_list'
    ),
    url(
        r'^ime_power_measure/(?P<id>[-\w]+)/$',
        views.Ime_power_measureRetrieveUpdateDestroyAPIView.as_view(),
        name='ime_power_measure_detail'
    ),
    url(
        r'^ime_power_measure/set-status/(?P<pk>\w+)/$',
        views.Ime_power_measureSetStatusView.as_view(),
        name='ime_power_measure_set_status'
    ),
    url(
        r'^ime_power_measure/enable/(?P<pk>\w+)/$',
        views.Ime_power_measureEnableView.as_view(),
        name='ime_power_measure_enable'
    ),
    url(
        r'^ime_power_measure/disable/(?P<pk>\w+)/$',
        views.Ime_power_measureDisableView.as_view(),
        name='ime_power_measure_disable'
    ),
    url(
        r'^installation/$',
        views.InstallationListCreateAPIView.as_view(),
        name='installation_list'
    ),
    url(
        r'^installation/(?P<id>[-\w]+)/$',
        views.InstallationRetrieveUpdateDestroyAPIView.as_view(),
        name='installation_detail'
    ),
    url(
        r'^installation/set-status/(?P<pk>\w+)/$',
        views.InstallationSetStatusView.as_view(),
        name='installation_set_status'
    ),
    url(
        r'^installation/enable/(?P<pk>\w+)/$',
        views.InstallationEnableView.as_view(),
        name='installation_enable'
    ),
    url(
        r'^installation/disable/(?P<pk>\w+)/$',
        views.InstallationDisableView.as_view(),
        name='installation_disable'
    ),
    url(
        r'^light_management_measure/$',
        views.Light_management_measureListCreateAPIView.as_view(),
        name='light_management_measure_list'
    ),
    url(
        r'^light_management_measure/(?P<id>[-\w]+)/$',
        views.Light_management_measureRetrieveUpdateDestroyAPIView.as_view(),
        name='light_management_measure_detail'
    ),
    url(
        r'^light_management_measure/set-status/(?P<pk>\w+)/$',
        views.Light_management_measureSetStatusView.as_view(),
        name='light_management_measure_set_status'
    ),
    url(
        r'^light_management_measure/enable/(?P<pk>\w+)/$',
        views.Light_management_measureEnableView.as_view(),
        name='light_management_measure_enable'
    ),
    url(
        r'^light_management_measure/disable/(?P<pk>\w+)/$',
        views.Light_management_measureDisableView.as_view(),
        name='light_management_measure_disable'
    ),
    url(
        r'^light_management_module/$',
        views.Light_management_moduleListCreateAPIView.as_view(),
        name='light_management_module_list'
    ),
    url(
        r'^light_management_module/(?P<id>[-\w]+)/$',
        views.Light_management_moduleRetrieveUpdateDestroyAPIView.as_view(),
        name='light_management_module_detail'
    ),
    url(
        r'^light_management_module/set-status/(?P<pk>\w+)/$',
        views.Light_management_moduleSetStatusView.as_view(),
        name='light_management_module_set_status'
    ),
    url(
        r'^light_management_module/enable/(?P<pk>\w+)/$',
        views.Light_management_moduleEnableView.as_view(),
        name='light_management_module_enable'
    ),
    url(
        r'^light_management_module/disable/(?P<pk>\w+)/$',
        views.Light_management_moduleDisableView.as_view(),
        name='light_management_module_disable'
    ),
    url(
        r'^light_profile/$',
        views.Light_profileListCreateAPIView.as_view(),
        name='light_profile_list'
    ),
    url(
        r'^light_profile/(?P<id>[-\w]+)/$',
        views.Light_profileRetrieveUpdateDestroyAPIView.as_view(),
        name='light_profile_detail'
    ),
    url(
        r'^light_profile/set-status/(?P<pk>\w+)/$',
        views.Light_profileSetStatusView.as_view(),
        name='light_profile_set_status'
    ),
    url(
        r'^light_profile/enable/(?P<pk>\w+)/$',
        views.Light_profileEnableView.as_view(),
        name='light_profile_enable'
    ),
    url(
        r'^light_profile/disable/(?P<pk>\w+)/$',
        views.Light_profileDisableView.as_view(),
        name='light_profile_disable'
    ),
    url(
        r'^light_profile_slot/$',
        views.Light_profile_slotListCreateAPIView.as_view(),
        name='light_profile_slot_list'
    ),
    url(
        r'^light_profile_slot/(?P<id>[-\w]+)/$',
        views.Light_profile_slotRetrieveUpdateDestroyAPIView.as_view(),
        name='light_profile_slot_detail'
    ),
    url(
        r'^light_profile_slot/set-status/(?P<pk>\w+)/$',
        views.Light_profile_slotSetStatusView.as_view(),
        name='light_profile_slot_set_status'
    ),
    url(
        r'^light_profile_slot/enable/(?P<pk>\w+)/$',
        views.Light_profile_slotEnableView.as_view(),
        name='light_profile_slot_enable'
    ),
    url(
        r'^light_profile_slot/disable/(?P<pk>\w+)/$',
        views.Light_profile_slotDisableView.as_view(),
        name='light_profile_slot_disable'
    ),
    url(
        r'^motion_event/$',
        views.Motion_eventListCreateAPIView.as_view(),
        name='motion_event_list'
    ),
    url(
        r'^motion_event/(?P<id>[-\w]+)/$',
        views.Motion_eventRetrieveUpdateDestroyAPIView.as_view(),
        name='motion_event_detail'
    ),
    url(
        r'^motion_event/set-status/(?P<pk>\w+)/$',
        views.Motion_eventSetStatusView.as_view(),
        name='motion_event_set_status'
    ),
    url(
        r'^motion_event/enable/(?P<pk>\w+)/$',
        views.Motion_eventEnableView.as_view(),
        name='motion_event_enable'
    ),
    url(
        r'^motion_event/disable/(?P<pk>\w+)/$',
        views.Motion_eventDisableView.as_view(),
        name='motion_event_disable'
    ),
    url(
        r'^node/$',
        views.NodeListCreateAPIView.as_view(),
        name='node_list'
    ),
    url(
        r'^node/(?P<id>[-\w]+)/$',
        views.NodeRetrieveUpdateDestroyAPIView.as_view(),
        name='node_detail'
    ),
    url(
        r'^node/set-status/(?P<pk>\w+)/$',
        views.NodeSetStatusView.as_view(),
        name='node_set_status'
    ),
    url(
        r'^node/enable/(?P<pk>\w+)/$',
        views.NodeEnableView.as_view(),
        name='node_enable'
    ),
    url(
        r'^node/disable/(?P<pk>\w+)/$',
        views.NodeDisableView.as_view(),
        name='node_disable'
    ),
    url(
        r'^node_module/$',
        views.Node_moduleListCreateAPIView.as_view(),
        name='node_module_list'
    ),
    url(
        r'^node_module/(?P<id>[-\w]+)/$',
        views.Node_moduleRetrieveUpdateDestroyAPIView.as_view(),
        name='node_module_detail'
    ),
    url(
        r'^node_module/set-status/(?P<pk>\w+)/$',
        views.Node_moduleSetStatusView.as_view(),
        name='node_module_set_status'
    ),
    url(
        r'^node_module/enable/(?P<pk>\w+)/$',
        views.Node_moduleEnableView.as_view(),
        name='node_module_enable'
    ),
    url(
        r'^node_module/disable/(?P<pk>\w+)/$',
        views.Node_moduleDisableView.as_view(),
        name='node_module_disable'
    ),
    url(
        r'^wilamp_alert/$',
        views.Wilamp_alertListCreateAPIView.as_view(),
        name='wilamp_alert_list'
    ),
    url(
        r'^wilamp_alert/(?P<id>[-\w]+)/$',
        views.Wilamp_alertRetrieveUpdateDestroyAPIView.as_view(),
        name='wilamp_alert_detail'
    ),
    url(
        r'^wilamp_alert/set-status/(?P<pk>\w+)/$',
        views.Wilamp_alertSetStatusView.as_view(),
        name='wilamp_alert_set_status'
    ),
    url(
        r'^wilamp_alert/enable/(?P<pk>\w+)/$',
        views.Wilamp_alertEnableView.as_view(),
        name='wilamp_alert_enable'
    ),
    url(
        r'^wilamp_alert/disable/(?P<pk>\w+)/$',
        views.Wilamp_alertDisableView.as_view(),
        name='wilamp_alert_disable'
    ),
    url(
        r'^feeder_pillar/$',
        views.Feeder_pillarListCreateAPIView.as_view(),
        name='feeder_pillar_list'
    ),
    url(
        r'^feeder_pillar/(?P<id>[-\w]+)/$',
        views.Feeder_pillarRetrieveUpdateDestroyAPIView.as_view(),
        name='feeder_pillar_detail'
    ),
    url(
        r'^feeder_pillar/set-status/(?P<pk>\w+)/$',
        views.Feeder_pillarSetStatusView.as_view(),
        name='feeder_pillar_set_status'
    ),
    url(
        r'^feeder_pillar/enable/(?P<pk>\w+)/$',
        views.Feeder_pillarEnableView.as_view(),
        name='feeder_pillar_enable'
    ),
    url(
        r'^feeder_pillar/disable/(?P<pk>\w+)/$',
        views.Feeder_pillarDisableView.as_view(),
        name='feeder_pillar_disable'
    ),
    url(
        r'^twilight_management_module/$',
        views.Twilight_management_moduleListCreateAPIView.as_view(),
        name='twilight_management_module_list'
    ),
    url(
        r'^twilight_management_module/(?P<id>[-\w]+)/$',
        views.Twilight_management_moduleRetrieveUpdateDestroyAPIView.as_view(),
        name='twilight_management_module_detail'
    ),
    url(
        r'^twilight_management_module/set-status/(?P<pk>\w+)/$',
        views.Twilight_management_moduleSetStatusView.as_view(),
        name='twilight_management_module_set_status'
    ),
    url(
        r'^twilight_management_module/enable/(?P<pk>\w+)/$',
        views.Twilight_management_moduleEnableView.as_view(),
        name='twilight_management_module_enable'
    ),
    url(
        r'^twilight_management_module/disable/(?P<pk>\w+)/$',
        views.Twilight_management_moduleDisableView.as_view(),
        name='twilight_management_module_disable'
    ),
    url(
        r'^twilight_measure/$',
        views.Twilight_measureListCreateAPIView.as_view(),
        name='twilight_measure_list'
    ),
    url(
        r'^twilight_measure/(?P<id>[-\w]+)/$',
        views.Twilight_measureRetrieveUpdateDestroyAPIView.as_view(),
        name='twilight_measure_detail'
    ),
    url(
        r'^twilight_measure/set-status/(?P<pk>\w+)/$',
        views.Twilight_measureSetStatusView.as_view(),
        name='twilight_measure_set_status'
    ),
    url(
        r'^twilight_measure/enable/(?P<pk>\w+)/$',
        views.Twilight_measureEnableView.as_view(),
        name='twilight_measure_enable'
    ),
    url(
        r'^twilight_measure/disable/(?P<pk>\w+)/$',
        views.Twilight_measureDisableView.as_view(),
        name='twilight_measure_disable'
    ),
    url(
        r'^motion_management_module/$',
        views.Motion_management_moduleListCreateAPIView.as_view(),
        name='motion_management_module_list'
    ),
    url(
        r'^motion_management_module/(?P<id>[-\w]+)/$',
        views.Motion_management_moduleRetrieveUpdateDestroyAPIView.as_view(),
        name='motion_management_module_detail'
    ),
    url(
        r'^motion_management_module/set-status/(?P<pk>\w+)/$',
        views.Motion_management_moduleSetStatusView.as_view(),
        name='motion_management_module_set_status'
    ),
    url(
        r'^motion_management_module/enable/(?P<pk>\w+)/$',
        views.Motion_management_moduleEnableView.as_view(),
        name='motion_management_module_enable'
    ),
    url(
        r'^motion_management_module/disable/(?P<pk>\w+)/$',
        views.Motion_management_moduleDisableView.as_view(),
        name='motion_management_module_disable'
    ),
    url(r'^user/change-password/',
        views.UserChangePasswordView.as_view(),
        name='users_change_password'
        ),
    url(r'^search/installations',
        views.InstallationSearchView.as_view(),
        name='search'
        ),
    url(r'^$', views.api_root, name='api_root'),
]
