# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wicloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='assets_managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='assets_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='installation_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='installator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instalator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
