# Generated by Django 2.1.1 on 2018-09-27 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='timezone_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_mty_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_mty_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_mty_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_mty_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_old_lamps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_without_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_energy_without_dim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='burning_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='end_interval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='end_interval_active_energy_counter_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='end_interval_measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='end_interval_reactive_energy_counter_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='light_management_module_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='mac',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='node_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='reactive_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='reactive_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='start_interval',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='start_interval_active_energy_counter_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='start_interval_measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='start_interval_reactive_energy_counter_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='iac_calibration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='nominal_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='old_lamp_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='pat_calibration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='power_losses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='pre_calibration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='vac_calibration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='energy_meter_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Energy_meter_module'),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='iac_hh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='iac_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='iac_ll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='iac_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='iac_peak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='mac',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='node_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='node_hms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='source_module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='vac_peak',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='vac_rms_absolute_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='vac_rms_absolute_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='vac_rms_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_peak_measure',
            name='vac_rms_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='adc_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='entity_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='error_resolved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='error_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='is_in_error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='jhi_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='light_level_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='logged_entity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='logged_entity_mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_adc_mismatch',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='adc_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='entity_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='error_resolved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='error_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='is_in_error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='jhi_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='light_level_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='logged_entity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='logged_entity_mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_light_level_and_power_mismatch',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='entity_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='error_resolved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='error_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='is_in_error',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='logged_entity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='error_node_offline',
            name='logged_entity_mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='max_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feeder_pillar',
            name='reference_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='coordinator_mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='file_name_encryption_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_uuid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='hardware_informations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='hardware_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Installation'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ready_to_receive_data',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Address'),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='counter_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Gateway'),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='gateway_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='rs_485_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_counter',
            name='rs_485_bus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='active_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='freq',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='ime_power_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Ime_power_counter'),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='jhi_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='jhi_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='operating_time_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='partial_active_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='power_counter_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='power_factor_sector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ime_power_measure',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Address'),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Customer'),
        ),
        migrations.AddField(
            model_name='installation',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='preparation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='active_energy_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='active_power_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='ad_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='ad_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='ad_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='ad_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='day_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='iac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='lamp_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='light_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='light_management_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Light_management_module'),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='lqi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='manual_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='measure_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='motion_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='node_fw_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='node_hms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='node_life',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='node_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='packets_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='packets_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='packets_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='parameters_crc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='parent_node',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='processing_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='profile_crc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='pw_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='pw_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='pw_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='pw_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='reactive_energy_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='reactive_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='source_module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='status_bitmask',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='vac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_measure',
            name='vcc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='device_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='lamp_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='light_profile_crc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='light_profile_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='light_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='timer_auto_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_management_module',
            name='timer_hps_protection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='gateway_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='jhi_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='light_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='profile_crc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='dof',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='don',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='eas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='ecr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='edw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='emo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='fade_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='fade_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='light_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Light_profile'),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='light_profile_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='mi_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='mi_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='mi_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='mi_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='motion_delay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='motion_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='motion_fade_in',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='motion_fade_out',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='pw_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='pw_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='pw_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='pw_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='tof',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='light_profile_slot',
            name='ton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='mac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='motion_broadcast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='motion_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='motion_management_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Motion_management_module'),
        ),
        migrations.AddField(
            model_name='motion_event',
            name='motion_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='adc_in_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='delay_after',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='fade_in',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='fade_out',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='mi_0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='mi_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='mi_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='mi_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='motion_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='motion_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='motion_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='retrigger_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motion_management_module',
            name='trigger_delay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Gateway'),
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='log_time_0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='log_time_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='log_time_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='log_time_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='log_time_ist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='mac',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='node',
            name='modules',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Node_module'),
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='time_zone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='time_zone_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node_module',
            name='energy_meter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Energy_meter_module'),
        ),
        migrations.AddField(
            model_name='node_module',
            name='light_management',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Light_management_module'),
        ),
        migrations.AddField(
            model_name='node_module',
            name='motion_management',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Motion_management_module'),
        ),
        migrations.AddField(
            model_name='node_module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='node_module',
            name='twilight_management',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Twilight_management_module'),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='adc_in_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='created_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='delay_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='lux_measured',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='number_average_measures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='persistence_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='programming_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='sampling_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='ths_sunrise_off',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='ths_sunrise_on',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='ths_sunset_off',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='ths_sunset_on',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='tw_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='tw_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='tw_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='valid_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_management_module',
            name='voltagem_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_measure',
            name='adc_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_measure',
            name='lux_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_measure',
            name='measure_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilight_measure',
            name='twilight_management_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Twilight_management_module'),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='alert_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='jhi_comment',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='jhi_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='log_class',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='logged_entity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='logged_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='logger_entity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='logger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='module',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='note',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='wilamp_alert',
            name='severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='energy_interval',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='energy_meter_module',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='energy_meter_peak_measure',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='error_light_level_and_adc_mismatch',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='error_light_level_and_power_mismatch',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='error_node_offline',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feeder_pillar',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ime_power_counter',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ime_power_measure',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='installation',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light_management_measure',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light_management_module',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light_profile',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light_profile_slot',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motion_event',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motion_management_module',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node_module',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twilight_management_module',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twilight_measure',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wilamp_alert',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
