# Generated by Django 2.0 on 2019-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='light_management_module',
            options={'ordering': ('ordering',), 'permissions': (('list_light_management_module', 'Can list light_management_module'), ('detail_light_management_module', 'Can detail light_management_module'), ('disable_light_management_module', 'Can disable light_management_module')), 'verbose_name': 'light_management_module', 'verbose_name_plural': 'light_management_modules'},
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='coordinator_mac',
            new_name='coordinatorMac',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='creation_date',
            new_name='creationDate',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='device_name',
            new_name='deviceName',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='file_name_encryption_info',
            new_name='fileNameEncryptionInfo',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='gateway_hostname',
            new_name='gatewayHostname',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='gateway_type',
            new_name='gatewayType',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='gateway_uuid',
            new_name='gatewayUUID',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='hardware_informations',
            new_name='hardwareInformations',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='hardware_model',
            new_name='hardwareModel',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='mac_address',
            new_name='macAddress',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='ready_to_receive_data',
            new_name='readyToReceiveData',
        ),
        migrations.RenameField(
            model_name='gateway',
            old_name='serial_number',
            new_name='serialNumber',
        ),
        migrations.AlterField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
    ]
