# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0002_auto_20181023_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='installator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installator', to=settings.AUTH_USER_MODEL),
        ),
    ]
