# Generated by Django 2.0 on 2019-03-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0002_auto_20190305_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy_interval',
            old_name='adcValue0',
            new_name='adc0Value',
        ),
        migrations.RenameField(
            model_name='energy_interval',
            old_name='adcValue1',
            new_name='adc1Value',
        ),
    ]
