# Generated by Django 2.0 on 2019-02-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wicloud', '0003_auto_20190111_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connected_device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('status', models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('logicId', models.CharField(blank=True, max_length=255, null=True)),
                ('userOwner', models.CharField(blank=True, max_length=255, null=True)),
                ('userType', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicloud_connected_device_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Gateway')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicloud_connected_device_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('nodes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Node')),
            ],
            options={
                'verbose_name': 'connected_device',
                'verbose_name_plural': 'connected_devices',
                'ordering': ('ordering',),
                'permissions': (('list_connected_device', 'Can list connected device'), ('detail_connected_device', 'Can detail connected device'), ('disable_connected_device', 'Can disable connected device')),
            },
        ),
        migrations.CreateModel(
            name='Light_fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('status', models.IntegerField(choices=[(0, 'disabled'), (1, 'enabled')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('serialNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('logicId', models.CharField(blank=True, max_length=255, null=True)),
                ('pLCode', models.CharField(blank=True, max_length=255, null=True)),
                ('userOwner', models.CharField(blank=True, max_length=255, null=True)),
                ('userType', models.CharField(blank=True, max_length=255, null=True)),
                ('userAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('userDistributionBox', models.CharField(blank=True, max_length=255, null=True)),
                ('userLightpoleMaterial', models.CharField(blank=True, max_length=255, null=True)),
                ('userLightpoleShape', models.CharField(blank=True, max_length=255, null=True)),
                ('userLightpoleHeight', models.CharField(blank=True, max_length=255, null=True)),
                ('timeZone', models.IntegerField(blank=True, null=True)),
                ('timeZoneCode', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicloud_light_fixture_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Gateway')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wicloud_light_fixture_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('nodes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Node')),
            ],
            options={
                'verbose_name': 'light_fixture',
                'verbose_name_plural': 'light_fixtures',
                'ordering': ('ordering',),
                'permissions': (('list_light_fixtures', 'Can list light fixtures'), ('detail_light_fixture', 'Can detail light fixtures'), ('disable_light_fixture', 'Can disable light fixtures')),
            },
        ),
        migrations.RenameField(
            model_name='energy_interval',
            old_name='activeEnergyMty0',
            new_name='burningTimeCounter',
        ),
        migrations.RenameField(
            model_name='energy_interval',
            old_name='activeEnergyMty1',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='energy_interval',
            old_name='activeEnergyMty2',
            new_name='nodeLifeCounter',
        ),
        migrations.RemoveField(
            model_name='energy_interval',
            name='activeEnergyMty3',
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Node'),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='userLampManufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='userLampModel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='userLampPower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='energy_meter_module',
            name='userLampType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ime_power_counter',
            name='gatewayUUID',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='energy_interval',
            name='lightFixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Light_fixture'),
        ),
        migrations.AddField(
            model_name='node',
            name='connectedDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Connected_device'),
        ),
        migrations.AddField(
            model_name='node',
            name='lightFixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wicloud.Light_fixture'),
        ),
    ]
