# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-23 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0004_auto_20181023_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='assets_managers',
            field=models.ManyToManyField(related_name='assets_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
