# Generated by Django 2.0 on 2019-03-07 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicloud', '0004_avg_power_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy_interval',
            old_name='duration',
            new_name='intervalDuration',
        ),
        migrations.AddField(
            model_name='avg_power_measure',
            name='intervalDuration',
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avg_power_measure',
            name='measureTimestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 11, 52, 39, 609826)),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='avg_power_measure',
            name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='avg_power_measure',
            unique_together={('mac', 'measureTimestamp', 'intervalDuration')},
        ),
        migrations.AlterUniqueTogether(
            name='energy_interval',
            unique_together={('mac', 'startInterval', 'intervalDuration')},
        ),
    ]
