version: 0.0
os: linux
files:
 - source: /
   destination: /var/www/wicloud
permissions:
  - object: /var/www/html/wicloud
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
 ApplicationStop:
  - location: codedeploy-scripts/stop.sh
    runas: ec2-user
 AfterInstall:
  - location: codedeploy-scripts/build.sh
    runas: ec2-user
 ApplicationStart:
  - location: codedeploy-scripts/start.sh
    runas: ec2-user


