import {BaseEntity} from '../../_models/base-entity';

export class LightManagementMeasureWilamp implements BaseEntity {
    constructor(
        public id?: number,
        public mac?: string,
        public processingStatus?: number,
        public nodeHMS?: string,
        public dayOfYear?: number,
        public measureType?: number,
        public parentNode?: string,
        public lqi?: number,
        public vac?: number,
        public vcc?: number,
        public iac?: number,
        public activePower?: number,
        public reactivePower?: number,
        public activeEnergyCounter?: number,
        public reactiveEnergyCounter?: number,
        public lightLevel?: number,
        public pw0?: number,
        public pw1?: number,
        public pw2?: number,
        public pw3?: number,
        public nodeTemp?: number,
        public ad0?: number,
        public ad1?: number,
        public ad2?: number,
        public ad3?: number,
        public packetsSent?: number,
        public packetsReceived?: number,
        public packetsLost?: number,
        public motionStatus?: number,
        public manualStatus?: number,
        public statusBitmask?: number,
        public parametersCRC?: number,
        public profileCRC?: number,
        public measureTimestamp?: any,
        public createdTimestamp?: any,
        public sourceModule?: string,
        public nodeFwVersion?: string,
        public lampLife?: number,
        public nodeLife?: number,
        public activePowerCounter?: number,
        public installationId?: number,
        public lightManagementModuleName?: string,
        public lightManagementModuleId?: number,
    ) {
    }
}
