version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "wicloud-test.wi4b.com"
        BUILD_ENV: "prod"
phases:
  install:
    commands:
        - codebuild-scripts/install.sh
  build:
    commands:
       - codebuild-scripts/build.sh
  post_build:
         commands:
          - codebuild-scripts/postbuild.sh
#artifacts:
#    files:
#        - '**/*'
#    discard-paths: yes
#    base-directory: 'angular/dist*'
